### ISSUE TITLE
Path to shacl.ttl is "/etc/shacl.ttl" while the file is in "/rdf/shacl.ttl"

### ISSUE THREAD

**Issue by tfrancart** [TopQuadrant/shacl#32]
Here : https://github.com/TopQuadrant/shacl/blob/master/src/main/java/org/topbraid/shacl/tools/AbstractTool.java#L51

This result in an exception when trying to run the tool from the command-line : 

Exception in thread "main" java.lang.NullPointerException: InputStream is null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:266)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:254)
	at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:69)
	at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:305)
	at org.topbraid.shacl.tools.AbstractTool.<init>(AbstractTool.java:53)
	at org.topbraid.shacl.tools.Validate.<init>(Validate.java:35)
	at org.topbraid.shacl.tools.Validate.main(Validate.java:38)

**Comment by HolgerKnublauch** [comment]
Oops, that should fix it https://github.com/TopQuadrant/shacl/commit/f39b8e84732a15bea94802f01538cf27a4ab1282

Can you confirm?

**Comment by tfrancart** [comment]
Confirmed !
