### ISSUE TITLE
NullPointerException on qualifiedMinCount

### ISSUE THREAD

**Issue by tfrancart** [TopQuadrant/shacl#34]
```
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.topbraid.shacl.js.NashornScriptEngine.createScriptReader(NashornScriptEngine.java:142)
	at org.topbraid.shacl.js.NashornScriptEngine.executeScriptFromURL(NashornScriptEngine.java:130)
	at org.topbraid.shacl.js.NashornScriptEngine.executeLibraries(NashornScriptEngine.java:120)
	at org.topbraid.shacl.js.NashornScriptEngine.executeLibraries(NashornScriptEngine.java:114)
	at org.topbraid.shacl.js.NashornScriptEngine.executeLibraries(NashornScriptEngine.java:114)
	at org.topbraid.shacl.validation.js.AbstractJSExecutor.executeConstraint(AbstractJSExecutor.java:79)
	at org.topbraid.shacl.validation.ValidationEngine.validateNodesAgainstConstraint(ValidationEngine.java:460)
	at org.topbraid.shacl.validation.ValidationEngine.validateNodesAgainstShape(ValidationEngine.java:399)
	at org.topbraid.shacl.validation.PropertyConstraintExecutor.executeConstraint(PropertyConstraintExecutor.java:46)
	at org.topbraid.shacl.validation.ValidationEngine.validateNodesAgainstConstraint(ValidationEngine.java:460)
	at org.topbraid.shacl.validation.ValidationEngine.validateAll(ValidationEngine.java:338)
	at org.topbraid.shacl.validation.ValidationUtil.validateModel(ValidationUtil.java:81)
	at org.topbraid.shacl.tools.Validate.run(Validate.java:48)
	at org.topbraid.shacl.tools.Validate.main(Validate.java:38)
SHACL Validation Failure: Could not execute JavaScript function "validateQualifiedMinCountProperty": java.lang.NullPointerException
```

My shapes file contain 1 instance of qualifiedMinCount :

```
nkls:CollectionShape a sh:NodeShape ;
	sh:name "Collection Nakala"@fr;
	sh:name "Nakala collection"@en;
	sh:description "Une collection Nakala (URI en '/collection')"@fr ;
	sh:targetClass skos:Concept ;
	# snip
	sh:property [
		sh:path dct:identifier ;
		sh:qualifiedValueShape [
			sh:pattern "^11280" ;
		] ;		
		sh:qualifiedMinCount 1 ;
	] ;
```

**Comment by tfrancart** [comment]
Sorry, this is me not using the latest codebase.
