### ISSUE TITLE
BrokenException when validating schema against SHACL schema

### ISSUE THREAD

**Issue by umbreak** [TopQuadrant/shacl#46]
Running `ValidationUtil.validateModel(schema, shapes, true)` against a schema where the shapes are the ones defined on the [SHACL spec](https://www.w3.org/ns/shacl-shacl)

```
org.apache.jena.shared.BrokenException: oh dear, already have a slot for http://www.w3.org/ns/shacl#PropertyShape , viz 759
    at org.apache.jena.mem.HashedBunchMap.grow(HashedBunchMap.java:109)
    at org.apache.jena.mem.HashedBunchMap.put$(HashedBunchMap.java:90)
    at org.apache.jena.mem.HashedBunchMap.put(HashedBunchMap.java:70)
    at org.apache.jena.mem.NodeToTriplesMapMem.add(NodeToTriplesMapMem.java:51)
    at org.apache.jena.mem.GraphTripleStoreBase.add(GraphTripleStoreBase.java:63)
    at org.apache.jena.mem.GraphMem.performAdd(GraphMem.java:37)
    at org.apache.jena.graph.impl.GraphBase.add(GraphBase.java:181)
    at org.apache.jena.riot.system.StreamRDFLib$ParserOutputGraph.triple(StreamRDFLib.java:181)
    at org.apache.jena.riot.lang.LangTurtle.emit(LangTurtle.java:57)
    at org.apache.jena.riot.lang.LangTurtleBase.emitTriple(LangTurtleBase.java:486)
    at org.apache.jena.riot.lang.LangTurtleBase.objectList(LangTurtleBase.java:352)
    at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectItem(LangTurtleBase.java:288)
    at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectList(LangTurtleBase.java:281)
    at org.apache.jena.riot.lang.LangTurtleBase.triplesBlankNode(LangTurtleBase.java:422)
    at org.apache.jena.riot.lang.LangTurtleBase.triplesBlankNode(LangTurtleBase.java:416)
    at org.apache.jena.riot.lang.LangTurtleBase.triplesNodeCompound(LangTurtleBase.java:404)
    at org.apache.jena.riot.lang.LangTurtleBase.triplesNode(LangTurtleBase.java:389)
    at org.apache.jena.riot.lang.LangTurtleBase.objectList(LangTurtleBase.java:351)
    at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectItem(LangTurtleBase.java:288)
    at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectList(LangTurtleBase.java:281)
    at org.apache.jena.riot.lang.LangTurtleBase.triples(LangTurtleBase.java:250)
    at org.apache.jena.riot.lang.LangTurtleBase.triplesSameSubject(LangTurtleBase.java:191)
    at org.apache.jena.riot.lang.LangTurtle.oneTopLevelElement(LangTurtle.java:46)
    at org.apache.jena.riot.lang.LangTurtleBase.runParser(LangTurtleBase.java:91)
    at org.apache.jena.riot.lang.LangBase.parse(LangBase.java:41)
    at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:191)
    at org.apache.jena.riot.RDFParser.read(RDFParser.java:352)
    at org.apache.jena.riot.RDFParser.parseNotUri(RDFParser.java:342)
    at org.apache.jena.riot.RDFParser.parse(RDFParser.java:291)
    at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:500)
    at org.apache.jena.riot.RDFDataMgr.parseFromInputStream(RDFDataMgr.java:870)
    at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:268)
    at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:254)
    at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:69)
    at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:305)
    at org.topbraid.shacl.util.SHACLSystemModel.getSHACLModel(SHACLSystemModel.java:49)
    at org.topbraid.shacl.validation.ValidationUtil.ensureToshTriplesExist(ValidationUtil.java:73)
```

**Comment by HolgerKnublauch** [comment]
Are you by any chance running this code in multi-threading? Does it happen consistently?

**Comment by umbreak** [comment]
We are running it against an API (akka-http) which is multithread, yes.
We have to investigate more to see if it happens consistently so far

**Comment by umbreak** [comment]
We are running it against an API (akka-http) which is multithread, yes.
We have to investigate more to see if it happens consistently so far

**Comment by willemneal** [comment]
I just tried this with the validation example and I got 

```

**Comment by umbreak** [comment]
I'll try that. But since it is not happening all the time it will take a while to be sure. Thanks
