### ISSUE TITLE
SPARQLRule Exception

### ISSUE THREAD

**Issue by willemneal** [TopQuadrant/shacl#47]
I tried to run the SPARQLRule example:
```
@prefix ex: <http://example.com#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix person: <http://datashapes.org/shasf/tests/rules/triple/person#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .

ex:InvalidRectangle
	a ex:Rectangle .

ex:NonSquareRectangle
	a ex:Rectangle ;
	ex:height 2 ;
	ex:width 3 .

ex:SquareRectangle
	a ex:Rectangle ;
	ex:height 4 ;
	ex:width 4 .




ex:RectangleShape
	a sh:NodeShape ;
	sh:targetClass ex:Rectangle ;
	sh:property [
		sh:path ex:width ;
		sh:datatype xsd:integer ;
		sh:minCount 1 ;
		sh:maxCount 1 ;
	] ;
	sh:property [
		sh:path ex:height ;
		sh:datatype xsd:integer ;
		sh:minCount 1 ;
		sh:maxCount 1 ;
	] .


ex:RectangleRulesShape
    a sh:NodeShape ;
    sh:targetClass ex:Rectangle ;
    sh:rule [
        a sh:SPARQLRule ;
        sh:prefixes ex: ;
        sh:construct """
            CONSTRUCT {
                $this ex:area ?area .
            }
            WHERE {
                $this ex:width ?width .
                $this ex:height ?height .
                BIND (?width * ?height AS ?area) .
            }
            """ ;
        sh:condition ex:RectangleShape ;    # Rule only applies to Rectangles that conform to ex:RectangleShape
    ] ;
.
```

Here is the java code:
```java
Model dataModel = JenaUtil.createMemoryModel();
dataModel.read(Object.class.getResourceAsStream("/sh/tests/rules/triple/data.ttl"), 
               "urn:dummy", FileUtils.langTurtle);
Model report = RuleUtil.executeRules(dataModel, dataModel, null, null);
```

And here is the exception:
```
Exception in thread "main" org.apache.jena.query.QueryParseException: Line 3, column 23: Unresolved prefixed name: ex:area
	at org.apache.jena.sparql.lang.ParserBase.throwParseException(ParserBase.java:522)
	at org.apache.jena.sparql.lang.ParserBase.resolvePName(ParserBase.java:287)
	at org.apache.jena.sparql.lang.arq.ARQParser.PrefixedName(ARQParser.java:5744)
	at org.apache.jena.sparql.lang.arq.ARQParser.iri(ARQParser.java:5728)
	at org.apache.jena.sparql.lang.arq.ARQParser.VarOrIri(ARQParser.java:3967)
	at org.apache.jena.sparql.lang.arq.ARQParser.Verb(ARQParser.java:3093)
	at org.apache.jena.sparql.lang.arq.ARQParser.PropertyListNotEmpty(ARQParser.java:3055)
	at org.apache.jena.sparql.lang.arq.ARQParser.TriplesSameSubject(ARQParser.java:3021)
	at org.apache.jena.sparql.lang.arq.ARQParser.TriplesTemplate(ARQParser.java:2188)
	at org.apache.jena.sparql.lang.arq.ARQParser.ConstructQuads(ARQParser.java:2076)
	at org.apache.jena.sparql.lang.arq.ARQParser.ConstructTemplate(ARQParser.java:2965)
	at org.apache.jena.sparql.lang.arq.ARQParser.ConstructQuery(ARQParser.java:537)
	at org.apache.jena.sparql.lang.arq.ARQParser.Query(ARQParser.java:33)
	at org.apache.jena.sparql.lang.arq.ARQParser.QueryUnit(ARQParser.java:21)
	at org.apache.jena.sparql.lang.ParserARQ$1.exec(ParserARQ.java:48)
	at org.apache.jena.sparql.lang.ParserARQ.perform(ParserARQ.java:96)
	at org.apache.jena.sparql.lang.ParserARQ.parse$(ParserARQ.java:52)
	at org.apache.jena.sparql.lang.SPARQLParser.parse(SPARQLParser.java:34)
	at org.apache.jena.query.QueryFactory.parse(QueryFactory.java:147)
	at org.topbraid.jenax.util.ARQFactory.doCreateQuery(ARQFactory.java:207)
	at org.topbraid.jenax.util.ARQFactory.doCreateQuery(ARQFactory.java:189)
	at org.topbraid.jenax.util.ARQFactory.createQuery(ARQFactory.java:179)
	at org.topbraid.shacl.rules.SPARQLRule.<init>(SPARQLRule.java:45)
	at org.topbraid.shacl.rules.SPARQLRuleLanguage.createRule(SPARQLRuleLanguage.java:25)
	at org.topbraid.shacl.rules.RuleEngine.getShapeRules(RuleEngine.java:228)
	at org.topbraid.shacl.rules.RuleEngine.executeShape(RuleEngine.java:133)
	at org.topbraid.shacl.rules.RuleEngine.executeShapes(RuleEngine.java:121)
	at org.topbraid.shacl.rules.RuleEngine.executeAll(RuleEngine.java:81)
	at org.topbraid.shacl.rules.RuleUtil.executeRulesHelper(RuleUtil.java:124)
	at org.topbraid.shacl.rules.RuleUtil.executeRules(RuleUtil.java:63)
	at org.topbraid.shacl.InferenceExample.main(InferenceExample.java:44)
```

**Comment by HolgerKnublauch** [comment]
Yeah this is a very common pitfall. The problem is that SHACL SPARQL cannot just use the prefixes that are declared in the Turtle file, but it needs to read them as RDF triples. See https://www.w3.org/TR/shacl/#sparql-prefixes

I wish it was simpler, but prefixes are not part of the RDF (graph) specification but only exist in various serializations of RDF and SPARQL. So: either don't use prefixes in your query, or redeclare them each time, or use sh:prefixes as explained in the spec.

(Please close if satisfied with the response).

**Comment by mrtnzagustin** [comment]
Hi @HolgerKnublauch ! I am using sh:prefixes and still have the error `Unresolved prefixed name: rdf:type`

```shacl
@prefix dash: <http://datashapes.org/dash#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix : <http://www.cibic.com.ar/ontologies/analisis-clinicos#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <http://www.cibic.com.ar/ontologies/analisis-clinicos> .

:IngresoRetenidoResultadoNumericoCritico a sh:NodeShape ;
    sh:targetClass :Ingreso;
	sh:rule [
		a sh:SPARQLRule ;
		sh:prefixes rdf: ;
		sh:construct """
            PREFIX : <http://www.cibic.com.ar/ontologies/analisis-clinicos#>
            PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
			CONSTRUCT {
				# Asigna la clase ResultadoCritico al resultado
				$resultado rdf:type :ResultadoCritico .
				
				# Asigna la clase IngresoRetenido al ingreso y le crea una validacion nueva
				$this 	rdf:type :IngresoRetenido ;
						:tieneValidacionPostAnalitica _:validacionGenerada.
				
				# Asigna a la validacion generada el parametro asociado y un detalle string
				_:validacionGenerada rdf:type :ValidacionPostAnalitica ;
									:tieneParametro ?parametroNumerico ;
									:detalle "Parámetro numérico en rango crítico"^^xsd:string .
			}
			WHERE {
				$this :tieneResultado ?resultado .
				
				$resultado 	rdf:type :ResultadoNumerico ;
							:valorResultadoNumerico ?valorResultadoNumerico ;
							:tieneParametro ?parametroNumerico.

				$parametroNumerico 	rdf:type :ParametroNumerico ;
									:tieneIntervaloCritico ?intervaloCritico ;
									:tieneIntervaloDeDecision ?intervaloDeDecision .
				
				?intervaloCritico 	rdf:type :IntervaloCritico ;
									:valorIntervaloInferior ?valorCriticoInferior ;
									:valorIntervaloSuperior ?valorCriticoSuperior .
				
				?intervaloDeDecision	rdf:type :IntervaloDeDecision ;
										:valorIntervaloInferior ?valorDeDecisionInferior ;
										:valorIntervaloSuperior ?valorDeDecisionSuperior .
				FILTER ( 
					(?valorResultadoNumerico > ?valorCriticoInferior 
						&& ?valorResultadoNumerico < ?valorDeDecisionInferior)
					 ||
					(?valorResultadoNumerico > ?valorDeDecisionSuperior 
						&& ?valorResultadoNumerico < ?valorCriticoSuperior)
				)
			}
			""" ;
	] .
```

**Comment by HolgerKnublauch** [comment]
sh:prefixes needs to point at an RDF resource that has sh:declare triples. The example above merely points at rdf: which probably doesn't have those triples. If you're inside TopBraid API code, usually the dash namespace contains the right declarations, so you could try sh:prefixes <http://datashapes.org/dash> instead of rdf:

For the spec, see https://www.w3.org/TR/shacl/#sparql-prefixes

**Comment by mrtnzagustin** [comment]
Great! Working now. Final test:

```shacl
:
	a owl:Ontology ;
	owl:imports sh: ;
	sh:declare [
		sh:prefix "" ;
		sh:namespace "http://www.cibic.com.ar/ontologies/analisis-clinicos#"^^xsd:anyURI ;
	] ;
	sh:declare [
		sh:prefix "xsd" ;
		sh:namespace "http://www.w3.org/2001/XMLSchema#"^^xsd:anyURI ;
	] ;
	sh:declare [
		sh:prefix "rdf" ;
		sh:namespace "http://www.w3.org/1999/02/22-rdf-syntax-ns#"^^xsd:anyURI ;
	] .

:IngresoRetenidoResultadoNumericoCritico a sh:NodeShape ;
    sh:targetClass :Ingreso;
	sh:rule [
		a sh:SPARQLRule ;
		sh:prefixes : ;
		sh:construct """
            CONSTRUCT {
				# Asigna la clase ResultadoCritico al resultado
				$resultado rdf:type :ResultadoCritico .
				
				# Asigna la clase IngresoRetenido al ingreso y le crea una validacion nueva
				$this 	rdf:type :IngresoRetenido ;
						:tieneValidacionPostAnalitica _:validacionGenerada.
				
				# Asigna a la validacion generada el parametro asociado y un detalle string
				_:validacionGenerada rdf:type :ValidacionPostAnalitica ;
									:tieneParametro ?parametroNumerico ;
									:detalle "Parámetro numérico en rango crítico"^^xsd:string .
			}
			WHERE {
				$this :tieneResultado ?resultado .
				
				$resultado 	rdf:type :ResultadoNumerico ;
							:valorResultadoNumerico ?valorResultadoNumerico ;
							:tieneParametro ?parametroNumerico.

				$parametroNumerico 	rdf:type :ParametroNumerico ;
									:tieneIntervaloCritico ?intervaloCritico ;
									:tieneIntervaloDeDecision ?intervaloDeDecision .
				
				?intervaloCritico 	rdf:type :IntervaloCritico ;
									:valorIntervaloInferior ?valorCriticoInferior ;
									:valorIntervaloSuperior ?valorCriticoSuperior .
				
				?intervaloDeDecision	rdf:type :IntervaloDeDecision ;
										:valorIntervaloInferior ?valorDeDecisionInferior ;
										:valorIntervaloSuperior ?valorDeDecisionSuperior .
				FILTER ( 
					(?valorResultadoNumerico > ?valorCriticoInferior 
						&& ?valorResultadoNumerico < ?valorDeDecisionInferior)
					 ||
					(?valorResultadoNumerico > ?valorDeDecisionSuperior 
						&& ?valorResultadoNumerico < ?valorCriticoSuperior)
				)
			}
			""" ;
	] .

```

Thanks @HolgerKnublauch
